apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: planka-ingress
  namespace: planka-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: planka-latest-hqy2.onrender.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: planka-service
                port:
                  number: 1337